FROM readsb_autogain_testing_base:latest

COPY autogain_test_data/stats.pb.test_data.tar.xz /autogain_test_data/stats.pb.test_data.tar.xz

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -xe && \
    apt-get update && \
    apt-get install xz-utils -y && \
    pushd "/autogain_test_data" && \
    ls -la && \
    tar xJvf ./stats.pb.test_data.tar.xz && \
    apt-get remove xz-utils -y && \
    apt-get autoremove -y

ENTRYPOINT [ "bash", "/scripts/autogain_test.sh" ]
