# hadolint ignore=DL3008,SC2086,SC2039,SC2068,DL3007
FROM readsb_autogain_testing_base:latest

COPY autogain_test_data/stats.pb.test_data.tar.xz /autogain_test_data/stats.pb.test_data.tar.xz

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# hadolint ignore=DL3008,SC2086,SC2039,SC2068,DL3007,DL3008,DL3006
RUN set -xe && \
    apt-get update && \
    apt-get install xz-utils -y --no-install-recommends && \
    pushd "/autogain_test_data" && \
    ls -la && \
    tar xJvf ./stats.pb.test_data.tar.xz && \
    apt-get remove xz-utils -y && \
    apt-get autoremove -y && \
    rm -rf /src/* /tmp/* /var/lib/apt/lists/*

ENTRYPOINT [ "bash", "/scripts/autogain_test.sh" ]
