#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# Ensure /var/run/lighttpd is created and has correct ownership
mkdir -p /var/run/lighttpd
chown -R readsb /var/run/lighttpd

# Launch webapp unless disabled
if [[ -z "$DISABLE_WEBAPP" ]]; then
    s6-setuidgid readsb /usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf || exit 0

    set -eo pipefail

    #shellcheck disable=SC2016
    s6-setuidgid readsb /usr/sbin/lighttpd \
        -f /etc/lighttpd/lighttpd.conf \
        -D \
        2>&1 | stdbuf -o0 awk '{print "[lighttpd] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

# If webapp disabled, sleep forever
else
    sleep 86400
fi
