#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# If troubleshooting:
if [[ -n "$DEBUG_LOGGING" ]]; then
    set -x
fi

if [[ "$READSB_DEVICE_TYPE" == "rtlsdr" ]]; then
    if [[ -n "$READSB_ENABLE_BIASTEE" ]]; then
        # Wait for readsb service to be down
        s6-svwait -D /run/s6/services/readsb
        pkill --signal 9 -ef "/usr/local/bin/readsb "
        sleep 1

        # enable bias tee
        rtl_biast -d "$READSB_RTLSDR_DEVICE" -b 1
    fi
fi
