#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# If gain is specified...
if [[ -n "$READSB_GAIN" ]]; then

    # If the user wants to use the autogain system...
    if [[ "$READSB_GAIN" == "autogain" ]]; then

        # Run autogain
        #shellcheck disable=SC2016
        bash /autogain.sh 2>&1 | stdbuf -o0 awk '{print "[autogain] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

        # Sleep for 15 mins
        sleep 900

    fi

else
    sleep 86400
fi
