#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# If gain is specified and user wants to use the autogain system...
if [[ -n "$READSB_GAIN" ]] && [[ "$READSB_GAIN" == "autogain" ]]; then
    set -eo pipefail

    # Run autogain
    #shellcheck disable=SC2016
    bash /scripts/autogain.sh 2>&1 | stdbuf -o0 awk '{print "[autogain] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

    # Sleep for 15 mins
    sleep "$AUTOGAIN_SERVICE_PERIOD"

else
    sleep 86400
fi
