#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [[ -z "$DISABLE_PERFORMANCE_GRAPHS" ]]; then

    # Set environment variables that these scripts expect

    graph_size="$READSB_GRAPH_SIZE"
    all_large="$READSB_GRAPH_ALL_LARGE"
    font_size="$READSB_GRAPH_FONT_SIZE"
    max_messages_line="$READSB_GRAPH_MAX_MESSAGES_LINE"
    lwidth="$READSB_GRAPH_LARGE_WIDTH"
    lheight="$READSB_GRAPH_LARGE_HEIGHT"
    swidth="$READSB_GRAPH_SMALL_WIDTH"
    sheight="$READSB_GRAPH_SMALL_HEIGHT"
    ul_message_rate=
    ul_aircraft=
    ul_tracks=
    ul_range=
    ul_maxima=
    ul_rate_per_aircraft=
    ul_adsb_cpu=
    ul_range_uat=
    export graph_size all_large font_size max_messages_line lwidth lheight swidth sheight
    export ul_message_rate ul_aircraft ul_tracks ul_range ul_maxima ul_rate_per_aircraft ul_adsb_cpu ul_range_uat

    # Define functions

    function run_graphs() {
        # $1 = timeframe (eg: 7d, 30d, 180d, 1y)
        if [[ -n "$VERBOSE_LOGGING" ]]; then
            #shellcheck disable=SC2016
            echo "Refreshing $1 graphs" | stdbuf -o0 awk '{print "[graphs] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
        fi
        ./graphs.sh "$1" > /dev/null 2>&1
    }

    # Wait 30 minutes
    sleep 1800

    pushd /usr/share/readsb/graphs > /dev/null || exit 1 

    if [[ -e "/tmp/.next_graphs_7d" ]]; then
        run_graphs 7d
        rm "/tmp/.next_graphs_7d"
        touch "/tmp/.next_graphs_30d"

    elif [[ -e "/tmp/.next_graphs_30d" ]]; then
        run_graphs 30d
        sleep 300
        run_graphs 7d
        rm "/tmp/.next_graphs_30d"
        touch "/tmp/.next_graphs_180d"

    elif [[ -e "/tmp/.next_graphs_180d" ]]; then
        run_graphs 180d
        sleep 300
        run_graphs 7d
        sleep 300
        run_graphs 30d
        rm "/tmp/.next_graphs_180d"
        touch "/tmp/.next_graphs_1y"

    elif [[ -e "/tmp/.next_graphs_1y" ]]; then
        run_graphs 1y
        sleep 300
        run_graphs 30d
        sleep 300
        run_graphs 7d
        sleep 300
        run_graphs 180d
        rm "/tmp/.next_graphs_1y"
        touch "/tmp/.next_graphs_7d"

    fi

    popd > /dev/null || exit 1 

else
    sleep 86400
fi
