#!/usr/bin/with-contenv bash
#shellcheck shell=bash

NOCOLOR='\033[0m'
LIGHTRED='\033[1;31m'

EXITCODE=0

# If troubleshooting:
if [[ -n "$DEBUG_LOGGING" ]]; then
    set -x
fi

# Check that if more than one rtlsdr, that we have a serial given
if [[ "$READSB_DEVICE_TYPE" == "rtlsdr" ]]; then
    # Prepare temp file
    biast_tempfile=$(mktemp)
    # Attempt to get devices
    rtl_biast > "$biast_tempfile" 2>&1 || true
    # Get number of devices
    num_devices=$(sed -n 's/^Found\s\+\([0-9]\+\)\s\+device(s):\s*$/\1/p' "$biast_tempfile")
    # If we have more than one device, we need a serial number
    if [[ "$num_devices" -gt 1 ]]; then
        if [[ -z "$READSB_RTLSDR_DEVICE" ]]; then
            echo -e "${NOCOLOR}ERROR: Multiple RTL-SDR devices present. Please set READSB_RTLSDR_DEVICE!${LIGHTRED}"
            EXITCODE=1
        fi
    fi
    rm "$biast_tempfile"
fi

exit $EXITCODE