---
name: Linting (Non-Image)

on:
  pull_request:
    branches:
      - main
      # only run these linters if markdown / yaml is updated
    paths:
      - '**.md'
      - '**.MD'
      - '**.yml'

jobs:
  yamllint:
    name: Run yamllint against YAML files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              line-length:
                max: 120
                level: warning

  markdownlint:
    name: Run markdownlint against markdown files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Pull markdownlint/markdownlint:latest Image
        run: docker pull markdownlint/markdownlint:latest
      - name: Run markdownlint against *.md files
        run: docker run --rm -i -v "$(pwd)":/workdir --workdir /workdir markdownlint/markdownlint:latest --rules ~MD013,~MD033,~MD026,~MD002,~MD022 $(find . -type f -iname '*.md' | grep -v '/.git/')
